name: ROS2 CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          rosdistro: [dashing, eloquent, master]
          os: [ubuntu-18.04, macOS-latest, windows-latest]
          exclude:
            # pending https://github.com/ament/ament_cmake/pull/233
            - rosdistro: eloquent
              os: windows-latest
            # pending https://github.com/ament/ament_cmake/pull/234
            - rosdistro: dashing
              os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Acquire ROS dependencies
      uses: ros-tooling/setup-ros@0.0.15
    - name: Build and test ROS
      uses: ros-tooling/action-ros-ci@0.0.14
      with:
        package-name: rmw_cyclonedds_cpp
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/${{ matrix.rosdistro }}/ros2.repos
