name: ROS2 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
          os: [ubuntu-latest, macOS-latest, windows-latest]
          rosdistro: [dashing, eloquent]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: ros-tooling/setup-ros@0.0.15
      with:
        required-ros-distributions: ${{ matrix.rosdistro }}
    - uses: ros-tooling/action-ros-ci@0.0.13
      
