name: ROS2 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.15
    - uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: rmw_cyclonedds_cpp, test_communication
